###GET
GET http://127.0.0.1:5000/api/notes
content-type: application/json


###GET 1
GET http://127.0.0.1:5000/api/notes/2
content-type: application/json


###POST Category
POST http://127.0.0.1:5000/api/categories
content-type: application/json

{
  "name": "Misc",
  "color": "#9e9e9e"
}

###POST
POST http://127.0.0.1:5000/api/notes
content-type: application/json

{
  "category": 1,
  "title" : "Welcome to Notes App",
  "description" : "Welcome to Notes App. This is your first note. You can edit or delete it, and start adding your own notes!"
}

###POST 2
POST http://127.0.0.1:5000/api/notes
content-type: application/json

{
  "category": 1,
  "title" : "Test Note",
  "description" : "It is a test note for testing purposes."
}

###PUT 2
PUT http://127.0.0.1:5000/api/notes/2
content-type: application/json

{
  "category": 1,
  "title" : "Updated Note Title",
  "description" : "This is the updated description of the note."
}


###GET Categories
GET http://127.0.0.1:5000/api/categories
content-type: application/json

