###GET
GET http://127.0.0.1:5000/api/notes
content-type: application/json


###GET 1
GET http://127.0.0.1:5000/api/notes/1
content-type: application/json

###POST
POST http://127.0.0.1:5000/api/notes
content-type: application/json

{
  "category": 1,
  "title" : "test title",
  "description" : "test description"
}


###PUT
PUT http://127.0.0.1:5000/api/notes/2
content-type: application/json

{
  "title" : "test update title",
  "description" : "test update description"
}

###DELETE
DELETE http://127.0.0.1:5000/api/notes/2
content-type: application/json

###POST Category
POST http://127.0.0.1:5000/api/categories
content-type: application/json

{
  "name": "Work",
  "color": "#2196f3"
}

###GET Categories
GET http://127.0.0.1:5000/api/categories
content-type: application/json

